name: Accent
favicon: null
layout_spectrum: 0.5759225117508322
typography_spectrum: 0.8942402845714241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.35362577717751265
  lightness: 0.992115224013105
  saturation: 0.9466680099721998
  rhythmicContrast: 0.5084263563621789
purpose: []
