name: Accent
favicon: null
layout_spectrum: 0.89741
typography_spectrum: 0.79792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4b2160'
    - '#ddd5e1'
    - '#7e608d'
    - '#a28cad'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
